#!/usr/bin/env python3

import argparse
import os
from pathlib import Path
import shutil
import subprocess
import sys

import cipher_config as config


BASE_DIR = Path(__file__).resolve().parent
CPP_PATH = BASE_DIR / "step2.cpp"
HEADER_PATH = BASE_DIR / "step2_generated_config.h"
EXE_PATH = BASE_DIR / "step2.exe"


def validate_config():
    errors = []
    expected_route_len = (
        config.characteristic_model_number * config.total_rounds + 1
    )

    if config.state_bits != 64:
        errors.append(f"state_bits must be 64, got {config.state_bits}")
    if config.key_bits != 128:
        errors.append(f"key_bits must be 128, got {config.key_bits}")
    if config.trail_model_number < 2:
        errors.append(
            f"trail_model_number must be at least 2, got {config.trail_model_number}"
        )
    if config.characteristic_model_number < 2:
        errors.append(
            "characteristic_model_number must be at least 2, got "
            f"{config.characteristic_model_number}"
        )
    if config.dim_truncated > config.basis_number:
        errors.append(
            f"dim_truncated ({config.dim_truncated}) must not exceed "
            f"basis_number ({config.basis_number})"
        )
    if not config.diffs:
        errors.append("diffs must contain at least one characteristic")

    for idx, characteristic in enumerate(config.diffs):
        if len(characteristic) != expected_route_len:
            errors.append(
                f"diffs[{idx}] has {len(characteristic)} entries; "
                f"expected {expected_route_len}"
            )

    if errors:
        raise ValueError("Invalid cipher_config.py:\n  - " + "\n  - ".join(errors))


def cpp_string(value):
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def format_characteristics():
    characteristic_blocks = []
    for characteristic in config.diffs:
        values = [f"0x{value:016x}ULL" for value in characteristic]
        rows = [
            "        " + ",".join(values[i:i + 4])
            for i in range(0, len(values), 4)
        ]
        characteristic_blocks.append("    {\n" + ",\n".join(rows) + "\n    }")
    return ",\n".join(characteristic_blocks)


def generated_header_text():
    analysis_indices = getattr(
        config,
        "analysis_characteristic_indices",
        list(range(min(4, len(config.diffs)))),
    )
    analysis_indices_cpp = ",".join(str(index) for index in analysis_indices)
    return f"""#pragma once

// Generated from cipher_config.py by run_all.py.
// Do not edit this file manually.
const int TOTAL_ROUNDS={config.total_rounds};
const int BEGIN_ROUND={config.begin_round};
const int BASIS_NUMBER={config.basis_number};
const int WEIGHT_RANGE={config.weight_range};
const std::string D_STR={cpp_string(config.d_str)};
const int TRAIL_NUMBER={config.trail_model_number};
const int ROUTE_NUMBER={config.characteristic_model_number};
const std::vector<int> ANALYSIS_CHARACTERISTIC_INDICES={{{analysis_indices_cpp}}};

const std::vector<std::vector<uint64_t>> diffs={{
{format_characteristics()}
}};
"""


def update_generated_header():
    content = generated_header_text()
    old_content = None
    if HEADER_PATH.exists():
        old_content = HEADER_PATH.read_text(encoding="utf-8")
    if old_content == content:
        return False
    HEADER_PATH.write_text(content, encoding="utf-8", newline="\n")
    return True


def find_compiler():
    configured = os.environ.get("CXX")
    if configured:
        compiler = shutil.which(configured)
        if compiler is None:
            raise FileNotFoundError(
                f"CXX={configured!r} was set, but the compiler was not found"
            )
        return compiler

    for candidate in ("g++", "clang++", "x86_64-w64-mingw32-g++"):
        compiler = shutil.which(candidate)
        if compiler is not None:
            return compiler

    raise FileNotFoundError(
        "No C++ compiler found. Install g++/clang++, or set the CXX environment variable."
    )


def executable_is_stale(header_changed):
    if header_changed or not EXE_PATH.exists():
        return True
    exe_mtime = EXE_PATH.stat().st_mtime
    return CPP_PATH.stat().st_mtime > exe_mtime or HEADER_PATH.stat().st_mtime > exe_mtime


def build_step2(header_changed):
    if not executable_is_stale(header_changed):
        print(f"[build] {EXE_PATH.name} is up to date", flush=True)
        return

    compiler = find_compiler()
    command = [
        compiler,
        "-O3",
        "-std=c++17",
        str(CPP_PATH),
        "-o",
        str(EXE_PATH),
    ]
    print("[build] " + " ".join(command), flush=True)
    subprocess.run(command, cwd=BASE_DIR, check=True)


def run_command(label, command):
    print(f"\n===== {label} =====", flush=True)
    print(" ".join(map(str, command)), flush=True)
    subprocess.run(command, cwd=BASE_DIR, check=True)


def print_config():
    print("GIFT-64 quasidifferential pipeline")
    print(f"  rounds          = {config.total_rounds}")
    print(f"  begin_round     = {config.begin_round}")
    print(f"  characteristics = {len(config.diffs)}")
    print(f"  characteristic_model_number = {config.characteristic_model_number}")
    print(
        "  characteristic_length       = "
        f"{config.characteristic_model_number * config.total_rounds + 1}"
    )
    print(f"  trail_model_number          = {config.trail_model_number}")
    print(
        "  trail_length                = "
        f"{config.trail_model_number * config.total_rounds + 1}"
    )
    print(f"  basis_number    = {config.basis_number}")
    print(f"  dim_truncated   = {config.dim_truncated}")
    print(f"  weight_range    = {config.weight_range}")
    print(f"  input_x         = {config.input_x}")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Run GIFT-64 quasidifferential steps using cipher_config.py"
    )
    parser.add_argument("--skip-step1", action="store_true")
    parser.add_argument("--only-step3", action="store_true")
    parser.add_argument(
        "--characteristic-limit",
        type=int,
        default=None,
        help=(
            "process only the first N characteristics; intended for the "
            "dominant-characteristic analysis and never overwrites the full "
            "Step-2 aggregate"
        ),
    )
    parser.add_argument(
        "--characteristic-analysis-only",
        action="store_true",
        help="run only the per-characteristic analysis in Step 3",
    )
    return parser.parse_args()


def main():
    args = parse_args()
    validate_config()
    if args.characteristic_limit is not None and args.characteristic_limit <= 0:
        raise ValueError("--characteristic-limit must be positive")
    if args.characteristic_analysis_only and args.characteristic_limit is None:
        raise ValueError(
            "--characteristic-analysis-only requires --characteristic-limit"
        )
    if args.characteristic_limit is not None and not args.characteristic_analysis_only:
        raise ValueError(
            "--characteristic-limit is reserved for the independent "
            "characteristic analysis; add --characteristic-analysis-only"
        )
    print_config()

    header_changed = update_generated_header()

    if args.only_step3:
        command = [sys.executable, str(BASE_DIR / "step3.py")]
        if args.characteristic_analysis_only:
            command.extend([
                "--characteristic-analysis-only",
                "--characteristic-limit",
                str(args.characteristic_limit),
            ])
        run_command("Step 3", command)
        return

    build_step2(header_changed)

    if not args.skip_step1:
        command = [sys.executable, str(BASE_DIR / "step1.py")]
        if args.characteristic_limit is not None:
            command.extend([
                "--characteristic-limit",
                str(args.characteristic_limit),
            ])
        run_command("Step 1", command)

    step2_command = [
        str(EXE_PATH),
        str(config.dim_truncated),
        str(config.input_x),
    ]
    if args.characteristic_limit is not None:
        step2_command.append(str(args.characteristic_limit))
    run_command("Step 2", step2_command)

    step3_command = [sys.executable, str(BASE_DIR / "step3.py")]
    if args.characteristic_analysis_only:
        step3_command.extend([
            "--characteristic-analysis-only",
            "--characteristic-limit",
            str(args.characteristic_limit),
        ])
    run_command("Step 3", step3_command)


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, RuntimeError, subprocess.CalledProcessError) as exc:
        print(f"\nERROR: {exc}", file=sys.stderr)
        sys.exit(1)
